ProjectMVC/Models/AutomovilViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ProjectMVC.Models
{
    public class AutomovilViewModel
    {
        [Required]
        [Display(Name = "Identificador")]
        public int Id { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [Display(Name = "Modelo")]
        [StringLength(50, ErrorMessage = "El másimo de carácteres para el {0} es de {2}", MinimumLength = 5)]
        public string Modelo { get; set; }

        [Required]
        [Display(Name = "Color")]
        [StringLength(15, ErrorMessage = "El másimo de carácteres para el {0} es de {2}", MinimumLength = 3)]
        public string Color { get; set; }

        [Required]
        [Display(Name = "No. de Placas")]
        [StringLength(10, ErrorMessage = "El másimo de carácteres para el {0} es de {2}", MinimumLength = 10)]
        public string Placas { get; set; }

        [Required]
        [Display(Name = "No. de Serie")]
        [StringLength(12, ErrorMessage = "El másimo de carácteres para el {0} es de {2}", MinimumLength = 12)]
        public string Serie { get; set; }

        [Required]
        [Display(Name = "No. de Puertas")]
        public int NumPuertas { get; set; }

        [Display(Name = "Cantidad de Ruedas")]
        public int NumRuedas { get; set; }

        [Required]
        [Display(Name = "Precio")]
        [DisplayFormat(DataFormatString = "{0:C}")]
        public decimal Precio { get; set; }
    }
}

ProjectMVC/Controllers/AutomovilController.cs
using ProjectMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectMVC.Controllers
{
    public class AutomovilController : Controller
    {
        // GET: Automovil
        public ActionResult Index()
        {
            ViewBag.MensajeListado = "Aquí se muestra el listado de todos los automóviles registrados.";
            return View();
        }

        // GET: Automovil/Details/5
        public ActionResult Details(int id)
        {

            return View();
        }

        // GET: Automovil/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Automovil/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Color,Precio")] AutomovilViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    // TODO: Add insert logic here

                    return RedirectToAction("Index");
                }
                return View(model);
            }
            catch
            {
                return View(model);
            }
        }

        // GET: Automovil/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Automovil/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Automovil/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Automovil/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ProjectMVC/Views/Automovil/Create.cshtml
@model ProjectMVC.Models.AutomovilViewModel

@{
    ViewBag.Title = "Crear un Automóvil";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Create", "Automovil", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Crear nuevo automóvil.</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Id, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Id, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Id, "", new { @class= "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Modelo, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Modelo, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Id, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Color, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            <input class="input-validation-error form-control" 
                   id="Color" name="Color" type="text" value="">
            @*@Html.TextBoxFor(m => m.Color, new { @class = "form-control" })*@
            @Html.ValidationMessageFor(m => m.Color, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Placas, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Placas, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Placas, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Serie, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Serie, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Serie, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.NumPuertas, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.NumPuertas, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.NumPuertas, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.NumRuedas, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.NumRuedas, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.NumRuedas, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Precio, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Precio, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Precio, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Registrar" />
        </div>
    </div>
}

ProjectMVC/Views/Automovil/Details.cshtml
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

ProjectMVC/Views/Automovil/Index.cshtml
@{
    ViewBag.Title = "Listado de Automóviles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<h4>@ViewBag.MensajeListado</h4>