ProjectMVC/Controllers/InstructoresController.cs
using ProjectMVC.Entidades;
using ProjectMVC.Negocio;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectMVC.Controllers
{
    public class InstructoresController : Controller
    {
        // GET: Instructores
        public ActionResult Index(int id)
        {
            InstructorNegocio negocio = new InstructorNegocio();
            ArchivoDTO archivo = negocio.ObtenerFotoInstructor(id);

            ViewBag.IdInstructor = id;

            return View(archivo);
        }

        [HttpPost]
        [ActionName("Index")]
        public ActionResult IndexUpload(int id)
        {
            InstructorNegocio negocio = new InstructorNegocio();

            if (Request.Files.Count > 0)
            {
                var file = Request.Files[0];

                if (file != null && file.ContentLength > 0)
                {
                    Stream strm = file.InputStream;
                    string[] cadenasExtension = file.ContentType.Split('/');

                    ArchivoDTO archivo = new ArchivoDTO()
                    {
                        Contenido = ObtenerBytes(strm),
                        Extension = cadenasExtension[cadenasExtension.Length-1]
                    };
                    negocio.ActualizarFotoInstructor(id, archivo);
                }
            }

            ArchivoDTO archivoBD = negocio.ObtenerFotoInstructor(id);
            return View(archivoBD);
        }

        [HttpGet]
        public FileResult DescargarFoto(int id)
        {
            InstructorNegocio negocio = new InstructorNegocio();
            ArchivoDTO archivo = negocio.ObtenerFotoInstructor(id);

            if (archivo != null && archivo.Contenido != null)
            {
                string nombreArchivo = string.Concat("foto.",archivo.Extension);
                string contentType = MimeMapping.GetMimeMapping(nombreArchivo);

                return File(archivo.Contenido, contentType, nombreArchivo);
            }
            return null;
        }

        private byte[] ObtenerBytes(Stream input)
        {
            using (MemoryStream ms = new MemoryStream())
            {
                input.CopyTo(ms);
                return ms.ToArray();
            }
        }
    }
}

ProjectMVC/Views/Instructores/Index.cshtml
@model ProjectMVC.Entidades.ArchivoDTO

@{
    ViewBag.Title = "Foto Instructor";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var base64 = Convert.ToBase64String(Model.Contenido);
    var imgSrc = String.Format("data:image/{0};base64,{1}", Model.Extension, base64);

    var idInstructor = ViewBag.IdInstructor;
}

<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-6">
        <h4>Foto de Base de datos</h4>
        <br />
        <img id="imgFoto" src="@imgSrc" />
    </div>
    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-6">
        <h4>Actualizar foto a base de datos</h4>
        @using (Html.BeginForm("Index", "Instructores", FormMethod.Post
                                    , new { enctype = "multipart/form-data" }))
        {
            <input type="file" name="file" />
            <input type="submit" id="btnActualizarFoto" value="Actualizar Foto"
                   class="form-control" />
        }
    </div>
    <input type="hidden" id="hdnId" value="@idInstructor" />
    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-6">
        <h4>Descarga de Foto</h4>
        <br />
        @Html.ActionLink("Descarga Foto aquí", "DescargarFoto", "Instructores"
                            , new { id = idInstructor }, new { @class="btn btn-primary" })
        <br />
        <button type="button" id="btnDescargarFoto" class="btn btn-success" 
               value="Descargar Foto Aquí">Descargar Foto Aquí</button>
    </div>
</div>

@section scripts{
    <script>
        $(document).ready(function () {

            $('#btnDescargarFoto').click(function () {
                window.location = '@Url.Action("DescargarFoto", "Instructores")?id=' + $('#hdnId').val();
            });

        });
    </script>
}