ProjectMVC/Models/ExamenesViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ProjectMVC.Models
{
    public class ExamenesViewModel
    {
        [Required]
        [Display(Name = "Identificador")]
        public short Id { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [Display(Name = "Nombre")]
        [StringLength(30, ErrorMessage = "El máximo de carácteres para el {0} es de {2}", MinimumLength = 5)]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [Display(Name = "Código")]
        [StringLength(8, ErrorMessage = "El máximo de carácteres para el {0} es de {2}", MinimumLength = 5)]
        public string Codigo { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [Display(Name = "Precio")]
        [DisplayFormat(DataFormatString = "{0:C}")]
        public decimal Precio { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [Display(Name = "Activo")]
        public bool Activo { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [Display(Name = "Tecnología")]
        public short IdTecnologia { get; set; }
    }
}

ProjectMVC/Controllers/ExamenesController.cs
using ProjectMVC.Entidades;
using ProjectMVC.Models;
using ProjectMVC.Models.Custom;
using ProjectMVC.Negocio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectMVC.Controllers
{
    public class ExamenesController : Controller
    {
        // GET: Examenes
        public ActionResult Index()
        {
            refSrvcServidor.ExamenContract examen = null;
            List<refSrvcServidor.ExamenContract> examenes = null;
            using (refSrvcServidor.IsrvcCertificadorClient servicio 
                = new refSrvcServidor.IsrvcCertificadorClient())
            {
                examen = servicio.ObtenerExamen(1);
                examenes = servicio.ObtenerExamenes();
            }

            string nombre = examen.Nombre;

            ViewBag.ListadoTecnologias = ObtenerListaTecnologias();

            return View();
        }

        // GET: Listado de Examenes
        public ActionResult _ListadoExamenes()
        {
            ExamenNegocio negocio = new ExamenNegocio();
            List<Examan> examenes = negocio.ObtenerListaExmanes();

            return PartialView(examenes);
        }

        // GET: Crear Examen
        public ActionResult CrearExamen()
        {
            ViewBag.ListadoTecnologias = ObtenerListaTecnologias();

            return View();
        }

        // POST: Crear Examen
        [HttpPost]
        public ActionResult CrearExamen(ExamenesViewModel modelo)
        {
            if (ModelState.IsValid)
            {
                ExamenNegocio negocio = new ExamenNegocio();

                Examan examen = new Examan()
                {
                    Id = 0,
                    Codigo = modelo.Codigo,
                    Nombre = modelo.Nombre,
                    Precio = modelo.Precio,
                    Activo = modelo.Activo,
                    IdTecnologia = modelo.IdTecnologia
                };

                negocio.GuardarExamen(examen);

                return RedirectToAction("Index");
            }

            ViewBag.ListadoTecnologias = ObtenerListaTecnologias();

            return View(modelo);
        }

        // POST: Editar Examen
        [HttpPost]
        public ActionResult EditarExamen(ExamenesViewModel modelo)
        {
            try
            {
                ExamenNegocio negocio = new ExamenNegocio();

                Examan examen = new Examan()
                {
                    Id = modelo.Id,
                    Codigo = modelo.Codigo,
                    Nombre = modelo.Nombre,
                    Precio = modelo.Precio,
                    Activo = modelo.Activo,
                    IdTecnologia = modelo.IdTecnologia
                };

                negocio.GuardarExamen(examen);

                return Json(new { status = "OK", mensaje = "El examen se ha guardado correctamente" });
            }
            catch (Exception ex)
            {
                return Json(new { status = "ERROR", mensaje = "Ocurrió un error al intentar guardar el examen Detalle: " + ex.Message });
            }
        }

        // POST: Eliminar Examen
        [HttpPost]
        public ActionResult EliminarExamen(short idExamen)
        {
            try
            {

                ExamenNegocio negocio = new ExamenNegocio();

                negocio.EliminarExamen(idExamen);

                return Json(new { status = "OK", mensaje = "El examen se ha eliminado correctamente" });
            }
            catch (Exception ex)
            {
                return Json(new { status = "ERROR", mensaje = "Ocurrió un error al intentar eliminar el examen. Detalle: " + ex.Message });
            }
        }

        private List<ListadoGenerico> ObtenerListaTecnologias()
        {
            try
            {
                TecnologiaNegocio negocio = new TecnologiaNegocio();
                List<Tecnologia> tecnologias = negocio.ObtenerTecnologiasActivas();

                List<ListadoGenerico> listado = new List<ListadoGenerico>();
                foreach (var tec in tecnologias)
                {
                    listado.Add(new ListadoGenerico()
                    {
                        Id = tec.Id,
                        Descripcion = tec.Descripcion

                    });
                }

                return listado;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

ProjectMVC/Views/Examenes/CrearExamen.cshtml
@model ProjectMVC.Models.ExamenesViewModel
@{
    ViewBag.Title = "Crear Examen";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("CrearExamen", "Examenes", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Crear nuevo automóvil.</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Codigo, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Codigo, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Codigo, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Nombre, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            <input class="form-control"
                   id="Nombre" name="Nombre" type="text" value="">
            @*@Html.TextBoxFor(m => m.Color, new { @class = "form-control" })*@
            @Html.ValidationMessageFor(m => m.Nombre, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Precio, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Precio, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Precio, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Activo, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.CheckBoxFor(m => m.Activo, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Activo, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.IdTecnologia, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.IdTecnologia, 
                new SelectList(ViewBag.ListadoTecnologias as List<ProjectMVC.Models.Custom.ListadoGenerico>, 
                "Id", "Descripcion") ,new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.IdTecnologia, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Registrar" />
        </div>
    </div>
}

ProjectMVC/Views/Examenes/Index.cshtml
@{
    ViewBag.Title = "Listado de Exámenes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-right">
        @Html.ActionLink("Agregar Nuevo Examen", "CrearExamen", "Examenes")
    </div>
</div>

<div id="dvListado">
</div>

<button id="btnAjaxWCF" type="button" class="btn btn-info">Probar Ajax WCF</button>
<br />
<div id="divAjaxWCF"></div>
<br />
<br />
<button id="btnListAjaxWCF" type="button" class="btn btn-primary">Probar Listado Ajax WCF</button>
<br />
<div id="divListAjaxWCF"></div>
<br />
<br />
<button id="btnImgAjaxWCF" type="button" class="btn btn-primary">Probar Imagen Ajax WCF</button>
<br />
<div id="divImgAjaxWCF"></div>

<input id="hdnIdExamen" value="" type="hidden" />
<div class="modal fade" id="modalEditar" tabindex="-1" role="dialog" aria-labelledby="editarModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="editarModalLabel">Editar Examen</h4>
            </div>
            <div class="modal-body">
                    <div class="form-group">
                        <label for="txtNombre" class="control-label">Nombre:</label>
                        <input type="text" class="form-control" id="txtNombre">
                    </div>
                    <div class="form-group">
                        <label for="txtCodigo" class="control-label">Código:</label>
                        <input type="text" class="form-control" id="txtCodigo">
                    </div>
                    <div class="form-group">
                        <label for="txtPrecio" class="control-label">Precio:</label>
                        <input type="text" class="form-control" id="txtPrecio">
                    </div>
                    <div class="form-group">
                        <label for="chkActivo" class="control-label">Activo:</label>
                        <input type="checkbox" class="form-control" id="chkActivo">
                    </div>
                    <div class="form-group">
                        <label for="selTecnologia" class="control-label">Tecnología:</label>
                        <select class="form-control" id="selTecnologia">
                            @foreach (var opcion in ViewBag.ListadoTecnologias as List<ProjectMVC.Models.Custom.ListadoGenerico>)
                            {
                                <option value="@opcion.Id">@opcion.Descripcion</option>
                            }
                        </select>
                    </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary" onclick="editarExamen();">Guardar</button>
            </div>
        </div>
    </div>
</div>

@section scripts{
<script src="~/Scripts/WCFAjax.js"></script>
    <script>
        function cargarExamenes() {
            // Cargar la vista parcial con la lista de examenes al div dvListado
            $('#dvListado').load('@(Url.Action("_ListadoExamenes","Examenes"))',
                function (response, status, xhr) {
                    if (status == "error") {
                        swal("Error","Ocurrió un error al cargar el listado de exámenes.","error");
                    }
                });
        }

        function editarExamen()
        {
            var examen = {
                Id: $('#hdnIdExamen').val(),
                Nombre: $('#txtNombre').val(),
                Codigo: $('#txtCodigo').val(),
                Precio: $('#txtPrecio').val(),
                Activo: $('#chkActivo').prop('checked'),
                IdTecnologia: $('#selTecnologia').val()
            }

            if (examen.Id <= 0) {
                swal("Aviso","No se encuentra el examen cargado correctamente, favor de volver a internatrlo","warning");
            }
            else if (examen.Nombre.length < 5) {
                swal("Aviso", "El Nombre debe tener mínimo 5 carácteres", "warning");
            }
            else if (examen.Codigo.length < 5) {
                swal("Aviso", "El Código debe tener mínimo 5 carácteres", "warning");
            }
            else if (examen.Precio <= 0) {
                swal("Aviso", "El Precio debe ser mayor a cero", "warning");
            }
            else {
                $.ajax({
                    type: "POST",
                    async: false,
                    url: '@Url.Action("EditarExamen","Examenes")',
                    data: JSON.stringify(examen),
                    contentType: "application/json",
                    datatType: "json",
                    error: function(xhr, status){
                        swal('Error en ajax ' + status);
                    },
                    success: function(data){
                        console.log(data);
                        swal(""+data.mensaje);
                        $('#modalEditar').modal('hide');
                        cargarExamenes();
                    }
                });
            }
        }

        function mostrarEditarExamen(id, nombre, codigo, precio, activo, idTecnologia){
            $('#hdnIdExamen').val(id);

            $('#txtNombre').val(nombre);
            $('#txtCodigo').val(codigo);
            $('#txtPrecio').val(precio);
            $('#chkActivo').prop('checked',activo);
            $('#selTecnologia').val(idTecnologia);

            $('#modalEditar').modal('show');
        }

        function eliminarExamen(id) {

            var examen = {
                idExamen: id
            }
            $.ajax({
                type: "POST",
                async: false,
                url: '@Url.Action("EliminarExamen", "Examenes")',
                data: JSON.stringify(examen),
                contentType: "application/json",
                datatType: "json",
                error: function (xhr, status) {
                    console.log(xhr);
                    swal('Error en ajax ' + status);
                },
                success: function (data) {
                    console.log(data);
                    swal("" + data.mensaje);
                    cargarExamenes();
                }
            });
        }

        function mostrarEliminarExamen(id, nombre, codigo) {
            swal({
                title: '¿Está seguro de eliminar el examen con código '
                        + codigo
                        + ' y nombre '
                        + nombre
                        + '?',
                text: "No será posible revertir este cambio!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                cancelButtonText: 'Cancelar',
                confirmButtonText: 'Aceptar'
            }).then(function () {
                eliminarExamen(id);
            });
        }

        $(document).ready(function () {
            cargarExamenes();

            $("#btnAjaxWCF").click(function () {
                var parametros = { idExamen: 1 };

                ajaxObjeto("divAjaxWCF", "http://localhost:52608/srvcAjax.svc/ObtenerExamen", parametros);

                return false;
            });

            $("#btnListAjaxWCF").click(function () {
                var parametros = {};

                ajaxListado("divListAjaxWCF", "http://localhost:52608/srvcAjax.svc/ObtenerExamenes", parametros);

                return false;
            });

            $("#btnImgAjaxWCF").click(function () {
                var parametros = {idInstructor: 1};

                ajaxImg("imgAjax", "divImgAjaxWCF", "http://localhost:52608/srvcAjax.svc/ObtenerFotoInstructor", parametros);

                return false;
            });
        });
    </script>
}

ProjectMVC/Views/Examenes/_ListadoExamenes.cshtml
@using ProjectMVC.Entidades;
@model List<Examan>

@if (Model != null && Model.Count > 0)
{
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <table class="table table-hover table-striped table-responsive">
                        <thead>
                            <tr>
                                <th>Código</th>
                                <th>Nombre</th>
                                <th>Precio</th>
                                <th>Activo</th>
                                <th>Tecnología</th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td class="text-center">@item.Codigo</td>
                                    <td class="text-left">@item.Nombre</td>
                                    <td class="text-right">@string.Format("{0:C}", item.Precio)</td>
                                    @if (item.Activo)
                                    {
                                        <td class="text-center text-success">Sí</td>
                                    }
                                    else
                                    {
                                        <td class="text-center text-danger">No</td>
                                    }
                                    <td>@item.Tecnologia.Descripcion</td>
                                    <td>
                                        <a href="#" onclick="mostrarEditarExamen(@item.Id,
                                                                            '@item.Nombre',
                                                                            '@item.Codigo',
                                                                            @item.Precio,
                                                                            @Json.Encode(item.Activo),
                                                                            @item.IdTecnologia)">Editar</a>
                                    </td>
                                    <td>
                                        <a href="#" onclick="mostrarEliminarExamen(@item.Id, 
                                                                                '@item.Nombre',
                                                                                '@item.Codigo')">Eliminar</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="3">Verifique los precios de los exámenes</td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
}
else
{
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    No se encontraron exámenes registrados
                </div>
            </div>
        </div>
    </div>
}