ProjectMVC/Controllers/CursosController.cs
using ProjectMVC.Entidades;
using ProjectMVC.Negocio;
using Rotativa;
using Rotativa.Options;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectMVC.Controllers
{
    public class CursosController : Controller
    {
        // GET: Cursos
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        
        public ActionResult ReporteConteoCursos()
        {
            return View();
        }

        public ActionResult _ListadoCursosConteo()
        {
            CursoNegocio negocio = new CursoNegocio();
            List<ConteoCursoDTO> conteo = negocio.ObtenerConteoPorCursoOfertado();

            return PartialView(conteo);
        }

        public ActionResult ExportarListadoCursosConteo()
        {
            var vistaPDF = new ViewAsPdf();
            vistaPDF.ViewName = "ReporteConteoCursos";
            vistaPDF.CustomSwitches = "--footer-left \"" + DateTime.Now.ToString("dd/MM/yyyy") + "\""
                                    + " --footer-right \"Página [page] de [toPage]\""
                                    + " --footer-font-size \"9\" --footer-spacing 3";
            vistaPDF.Model = null;
            vistaPDF.PageSize = Size.A4;
            vistaPDF.PageOrientation = Orientation.Landscape;

            var pdfBytes = vistaPDF.BuildPdf(ControllerContext);

            //string nombreArchivo = HttpUtility.UrlEncode("ReporteConteo.pdf", System.Text.Encoding.UTF8);

            ArchivoDTO archivo = new ArchivoDTO()
            {
                Contenido = pdfBytes,
                Extension = ".pdf"
            };

            Session["rptConeto"] = archivo;
            return Json("OK", JsonRequestBehavior.AllowGet);
        }

        public void DescargaArchivo()
        {
            if (Session["rptConeto"] != null)
            {
                ArchivoDTO archivo = Session["rptConeto"] as ArchivoDTO;
                Session.Remove("rptConeto");

                // Usar Response para realizar la descarga
                Response.Clear();
                Response.Buffer = true;
                Response.Charset = "";
                Response.ContentType = "application/pdf";
                Response.AddHeader("content-disposition","attachment; filename=Reporte."+archivo.Extension);
                Response.BinaryWrite(archivo.Contenido);
                Response.Flush();
                Response.End();
            }
        }
    }
}

ProjectMVC/Views/Cursos/Index.cshtml
@{
    ViewBag.Title = "Conteo de Cursos Ofertados";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>
<div class="row hidden-print">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-right">
        <div class="btn-group">
            <button type="button" id="btnImprimir" class="btn btn-primary"><i class="glyphicon glyphicon-print"></i> Imprimir</button>
            <button type="button" id="btnDescargarPDF" class="btn btn-danger"><i class="glyphicon glyphicon-file"></i> PDF</button>
        </div>
    </div>
</div>


<div id="dvListado">
</div>

@section scripts{
    <script>
        function cargarConteoCursos() {
            // Cargar la vista parcial con la lista del conteo de cursos al div dvListado
            $('#dvListado').load('@(Url.Action("_ListadoCursosConteo", "Cursos"))',
                function (response, status, xhr) {
                    if (status == "error") {
                        swal("Error", "Ocurrió un error al cargar el listado del conteo de cursos.", "error");
                    }
                });
        }

        function ExportarPDF()
        {
            $.ajax({
                method: "GET",
                async: true,
                url: '@Url.Action("ExportarListadoCursosConteo", "Cursos")',
                contentType: "application/json",
                dataType: "json",
                error: function (xhr, textStatus, errorThrown) {
                    swal("Error: " + textStatus);
                },
                success: function (data) {
                    if (data == "OK") {
                        window.location = '@Url.Action("DescargaArchivo", "Cursos")'
                    }
                }
            });
        }

        $(document).ready(function () {
            cargarConteoCursos();

            $('#btnDescargarPDF').click(function (event) {
                event.preventDefault();

                ExportarPDF();
            });

            $('#btnImprimir').click(function (event) {
                event.preventDefault();

                window.print();
            });

        });
    </script>
    }

ProjectMVC/Views/Cursos/ReporteConteoCursos.cshtml
@{
    ViewBag.Title = "Reporte de Conteo de Cursos Ofertados";
    Layout = "~/Views/Shared/_LayoutReportes.cshtml";
}

<h2>@ViewBag.Title</h2>

@Html.Action("_ListadoCursosConteo", "Cursos")

ProjectMVC/Views/Cursos/_ListadoCursosConteo.cshtml
@using ProjectMVC.Entidades;
@model List<ConteoCursoDTO>

@if (Model != null && Model.Count > 0)
{
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <table class="table table-hover table-striped table-responsive">
                        <thead>
                            <tr>
                                <th>Código</th>
                                <th>Nombre</th>
                                <th>Cantidad Cursos Ofertados</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td class="text-center">@item.Codigo</td>
                                    <td class="text-center">@item.Nombre</td>
                                    <td class="text-left">@item.CantidadCursosOfertados</td>
                                </tr>
                            }
                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="3">El conteo muestra la cantudad de cursos ofertados por cada curso registrado en el sistema</td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
}
else
{
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    No se encontraron cursos
                </div>
            </div>
        </div>
    </div>
}